django/inforet/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('irapp.urls')),
]

django/irapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
import views

urlpatterns = [

	url(r'^$', views.index, name = 'Index'),
	url(r'^register/$', views.register, name = 'Registration'),
	url(r'^login/$', views.login, name = 'Login'),
	url(r'^logout/$', views.logout, name = 'Logout'),
	url(r'^upload/$', views.upload, name = 'Upload'),
	url(r'^dashboard/$', views.dashboard, name = 'Dashboard'),
	url(r'^summaryAPI/$', views.summaryAPI, name='summaryAPI'),
]


if settings.DEBUG:
		urlpatterns += [
			url(r'^media/(?P<path>.*)$', serve, {
				'document_root': settings.MEDIA_ROOT,
				}),
		]

django/irapp/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class User(models.Model):
   firstname = models.CharField(max_length=50)
   lastname = models.CharField(max_length=50)
   email = models.CharField(max_length=50,primary_key=True)
   password = models.CharField(max_length=100)

   def __unicode__(self):
    	return self.email

class Audio(models.Model):
	id = models.AutoField(primary_key=True)
	name = models.FileField(upload_to="audio")
	email = models.ForeignKey(User)
	timestamp = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return self.name.name

def get_upload_to(instance, filename):
    return 'upload/%d/%s' % (instance.profile, filename)

class Summary(models.Model):
	summaryId = models.ForeignKey(Audio)
	name = models.FileField(upload_to=get_upload_to)
	
	def __unicode__(self):
	   	return self.name.name

class Sentiment(models.Model):
	sentimentId = models.ForeignKey(Audio)
	name = models.FileField(upload_to=get_upload_to)
	
	def __unicode__(self):
	   	return self.name.name

django/templates/base.html
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Home</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="/dashboard">Dashboard</a></li>
        </ul>
        {% if request.COOKIES.username %}
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/logout">Logout</a></li>
        </ul>     
        {% elif request.path == "/login/" %}
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/register">Register</a></li>
        </ul>  
        {% else %}
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/login">Login</a></li>
        </ul>     
        {% endif %}
      </div><!--/.nav-collapse -->
    </div>
  </nav>
{% block content %}
{% endblock %}

django/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="icon" href="../../favicon.ico">

	<title>Student List</title>

	<!-- Bootstrap core CSS -->
	<link href="/static/css/bootstrap.min.css" rel="stylesheet">

	<!-- Custom styles for this template -->
	<link href="/static/css/dashboard.css" rel="stylesheet">
	<style>

	/*.axis .domain {
	  display: none;
	}*/
	.fit{
	    position: relative;
	    display: table;
	    overflow-y: auto;    
	    overflow-x: auto;
	    width: auto;
	    min-width: 800px;   
	}

	</style>

</head>

<body>

	{% extends "base.html" %}
	
	{% block content %}
	
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-8 col-sm-8 col-md-offset-2 col-sm-offset-2 main">
					<div class="col-md-12 page-header col-sm-12">
						<div class="col-md-6 col-sm-6">
							<h1>Audios</h1>
						</div>
						<div class="col-md-3 col-md-offset-3 col-sm-3 col-sm-offset-3 sub">
							<a href="/upload"><button name="upload" class="btn btn-success" >Upload New Audio</button></a>
						</div>
					</div>
					
   
    
				<form type="get" action=".">
					<div class="row">
						<div class="col-md-12 col-sm-12">
							<input type="text" id="search" class="form-control"  placeholder="Search..."> <br>
						</div>
					</div>
				</form>


				<div class="table-responsive">
					<table class="table table-striped tab">
						<thead class="thead-inverse">
							<tr>
								<th>Audio</th>
								<th>Summary</th>
								<th>Graph</th>
								<th>Uploaded Date</th>
							</tr>
						</thead>

						<tbody>
							{% for i in data %}
							<tr>
								<td><a href="/media/audio/{{i.0}}">{{i.0}}</a></td>
								<td><button value="/media/{{i.1}}" class="btnSummary btn btn-warning" type="button">View</button></td>
								<td><button name="adm" value="/media/{{i.2}}" class="btnGraph btn btn-info" type="button">View</button></td>
								<td>{{i.3}}</td>
							</tr>
							{%endfor%}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

	<div class="modal fade" id="graph" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	    <div class="modal-dialog fit">
	        <div class="modal-content">
	            <div class="modal-header">
	                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	                 <h3 class="modal-title" id="myModalLabel">Graph</h3>
	            </div>
	            <div class="modal-body">
	            	<svg width="960" height="500"></svg>
	            </div>
	            <div class="modal-footer">
	                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	            </div>
	        </div>
	    </div>
	</div>

	<div class="modal fade" id="summary" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	    <div class="modal-dialog">
	        <div class="modal-content">
	            <div class="modal-header">
	                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	                 <h3 class="modal-title" id="myModalLabel">Summary</h3>
	            </div>
	            <div class="modal-body" id="content">
	            	
	            </div>
	            <div class="modal-footer">
	                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	            </div>
	        </div>
	    </div>
	</div>
  

	    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/search.js"></script>
    <script src="https://d3js.org/d3.v4.min.js"></script>
    <script type="text/javascript">

    $('button.btnSummary').on('click', function(e){
	    var link = $(this).attr("value");
	    $('#summary').modal('show');
        $.ajax({
            url : link,
            dataType: "text",
            success : function (data) {
                $('#content').text(data);
            }
        });
	});

	$('button.btnGraph').on('click', function(e){
	    var link = $(this).attr("value");
	    generate(link)
	    $('#graph').modal('show');
	});

	function generate(link) {
		d3.selectAll("svg > *").remove();
    	var svg = d3.select("svg"),
	    margin = {top: 20, right: 20, bottom: 30, left: 40},
	    width = +svg.attr("width") - margin.left - margin.right,
	    height = +svg.attr("height") - margin.top - margin.bottom,
	    g = svg.append("g").attr("transform", "translate(" + margin.left + "," + margin.top + ")");

		var x0 = d3.scaleBand()
		    .rangeRound([0, width])
		    .paddingInner(0.1);

		var x1 = d3.scaleBand()
		    .padding(0.05);

		var y = d3.scaleLinear()
		    .rangeRound([height, 0]);

		var z = d3.scaleOrdinal()
		    .range(["#4CAF50", "#F57C00", "#D32F2F"]);
		
		console.log(link);
		var path = link
		d3.csv(path, function(d, i, columns) {
		  for (var i = 1, n = columns.length; i < n; ++i) d[columns[i]] = +d[columns[i]];
		  return d;
		}, function(error, data) {
		  if (error) throw error;

		  var keys = data.columns.slice(1);

		  x0.domain(data.map(function(d) { return d.State; }));
		  x1.domain(keys).rangeRound([0, x0.bandwidth()]);
		  y.domain([0, d3.max(data, function(d) { return d3.max(keys, function(key) { return 100; }); })]).nice();

		  g.append("g")
		    .selectAll("g")
		    .data(data)
		    .enter().append("g")
		      .attr("transform", function(d) { return "translate(" + x0(d.State) + ",0)"; })
		    .selectAll("rect")
		    .data(function(d) { return keys.map(function(key) { return {key: key, value: d[key]}; }); })
		    .enter().append("rect")
		      .attr("x", function(d) { return x1(d.key); })
		      .attr("y", function(d) { return y(d.value); })
		      .attr("width", x1.bandwidth())
		      .attr("height", function(d) { return height - y(d.value); })
		      .attr("fill", function(d) { return z(d.key); });

		  g.append("g")
		      .attr("class", "axis")
		      .attr("transform", "translate(0," + height + ")")
		      .call(d3.axisBottom(x0));

		  g.append("g")
		      .attr("class", "axis")
		      .call(d3.axisLeft(y).ticks(null, "s"))
		    .append("text")
		      .attr("x", 2)
		      .attr("y", y(y.ticks().pop()) + 0.5)
		      .attr("dy", "0.32em")
		      .attr("fill", "#000")
		      .attr("font-weight", "bold")
		      .attr("text-anchor", "start")
		      .text("Sentiment(%)");

		  var legend = g.append("g")
		      .attr("font-family", "sans-serif")
		      .attr("font-size", 10)
		      .attr("text-anchor", "end")
		    .selectAll("g")
		    .data(keys.slice().reverse())
		    .enter().append("g")
		      .attr("transform", function(d, i) { return "translate(0," + i * 20 + ")"; });

		  legend.append("rect")
		      .attr("x", width - 19)
		      .attr("width", 19)
		      .attr("height", 19)
		      .attr("fill", z);

		  legend.append("text")
		      .attr("x", width - 24)
		      .attr("y", 9.5)
		      .attr("dy", "0.32em")
		      .text(function(d) { return d; });
		});

		}

	</script>
</body>
</html>

{% endblock %}

django/templates/graph.html
<!DOCTYPE html>
<html>
<head>
  <title>Audio Analysis</title>
  <link href="/static/css/border.css" rel="stylesheet">
  <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
  {% extends "base.html" %}
  
  {% block content %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-10 col-sm-10 col-md-offset-1 col-sm-offset-1 main">
        <div class="page-header">
          <h1>Summary</h1>
        </div>
        <div class="well">
          <p>
            {{summary}}
          </p>
        </div>
        <div class="page-header">
          <h1>Graph</h1>
        </div>
        <div class="buttons box">
          <div class="btn blue">
            <span>
              <svg width="960" height="500">
              </svg>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://d3js.org/d3.v4.min.js"></script>
  <script>

  var svg = d3.select("svg"),
  margin = {top: 20, right: 20, bottom: 30, left: 40},
  width = +svg.attr("width") - margin.left - margin.right,
  height = +svg.attr("height") - margin.top - margin.bottom,
  g = svg.append("g").attr("transform", "translate(" + margin.left + "," + margin.top + ")");

  var x0 = d3.scaleBand()
  .rangeRound([0, width])
  .paddingInner(0.1);

  var x1 = d3.scaleBand()
  .padding(0.05);

  var y = d3.scaleLinear()
  .rangeRound([height, 0]);

  var z = d3.scaleOrdinal()
  .range(["#4CAF50", "#F57C00", "#D32F2F"]);

  d3.csv("/media/" + "{{path}}" + "/data.csv", function(d, i, columns) {
    for (var i = 1, n = columns.length; i < n; ++i) d[columns[i]] = +d[columns[i]];
      return d;
  }, function(error, data) {
    if (error) throw error;

    var keys = data.columns.slice(1);

    x0.domain(data.map(function(d) { return d.State; }));
    x1.domain(keys).rangeRound([0, x0.bandwidth()]);
    y.domain([0, d3.max(data, function(d) { return d3.max(keys, function(key) { return 100; }); })]).nice();

    g.append("g")
    .selectAll("g")
    .data(data)
    .enter().append("g")
    .attr("transform", function(d) { return "translate(" + x0(d.State) + ",0)"; })
    .selectAll("rect")
    .data(function(d) { return keys.map(function(key) { return {key: key, value: d[key]}; }); })
    .enter().append("rect")
    .attr("x", function(d) { return x1(d.key); })
    .attr("y", function(d) { return y(d.value); })
    .attr("width", x1.bandwidth())
    .attr("height", function(d) { return height - y(d.value); })
    .attr("fill", function(d) { return z(d.key); });

    g.append("g")
    .attr("class", "axis")
    .attr("transform", "translate(0," + height + ")")
    .call(d3.axisBottom(x0));

    g.append("g")
    .attr("class", "axis")
    .call(d3.axisLeft(y).ticks(null, "s"))
    .append("text")
    .attr("x", 2)
    .attr("y", y(y.ticks().pop()) + 0.5)
    .attr("dy", "0.32em")
    .attr("fill", "#000")
    .attr("font-weight", "bold")
    .attr("text-anchor", "start")
    .text("Sentiment(%)");

    var legend = g.append("g")
    .attr("font-family", "sans-serif")
    .attr("font-size", 10)
    .attr("text-anchor", "end")
    .selectAll("g")
    .data(keys.slice().reverse())
    .enter().append("g")
    .attr("transform", function(d, i) { return "translate(0," + i * 20 + ")"; });

    legend.append("rect")
    .attr("x", width - 19)
    .attr("width", 19)
    .attr("height", 19)
    .attr("fill", z);

    legend.append("text")
    .attr("x", width - 24)
    .attr("y", 9.5)
    .attr("dy", "0.32em")
    .text(function(d) { return d; });
  });

</script>
</body>
</html>
{% endblock %}

django/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Audio Summarizer</title>

  <!-- CSS  -->

  <!-- Bootstrap core CSS -->
  <link href="/static/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/css/cover.css" rel="stylesheet">
  <style type="text/css">

  </style>

</head>
 <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Audio Analyser</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="#">Home</a></li>
                  {% if request.COOKIES.username %}
                  <li> <a href="/dashboard">Dashboard</a></li>
                    <li><a href="/logout">Logout</a></li>     
                  {% else %}
                    <li><a href="/login">Login</a></li>
                    <li><a href="/register">Register</a></li>
                  {% endif %}
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            <h1 class="cover-heading">Get Rich Analytics of your Audio in seconds!</h1>
            <!-- <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p> -->
            <p class="lead">
              {% if request.COOKIES.username %}
                <a href="/upload" class="btn btn-lg btn-default">Get Started</a>     
              {% else %}
                <a href="/login" class="btn btn-lg btn-default">Get Started</a>
              {% endif %}
            </p>
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>Made with <a href="http://getbootstrap.com">Bootstrap</a></p>
            </div>
          </div>

        </div>

      </div>

    </div>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="/static/js/bootstrap.min.js"></script>

  </body>
</html>

django/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="icon" href="../../favicon.ico">

	<title>Login</title>

	<!-- Bootstrap core CSS -->
	<link href="/static/css/bootstrap.min.css" rel="stylesheet">
	<link href="/static/css/signin.css" rel="stylesheet">
	<style type="text/css">
		h2 {
			text-align: center;
			margin-bottom: 20px;
			margin-top: 50px;
		}
	</style>

</head>

<body>
	{% extends "base.html" %}
	
	{% block content %}
	<div class="container">

		<form class="form-signin" action="/login/"  method="post">{%csrf_token%}
			<h2 class="form-signin-heading text-center">Please log in</h2>
			<label for="email" class="sr-only">Email</label>
			<input class="form-control" type="email" name="email" placeholder="Email" required autofocus>
			<label for="password" class="sr-only">Password</label>
			<input type="password" name="password" class="form-control" placeholder="Password" required>

			<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
		</form>

	</div> <!-- /container -->
</body>
</html>
{% endblock %}

django/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">

  <title>SignUp</title>

  <!-- Bootstrap core CSS -->
  <link href="/static/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/css/signin.css" rel="stylesheet">
  <style type="text/css">
    h2 {
      text-align: center;
      margin-bottom: 20px;
      margin-top: 50px;
    }
  </style>

</head>

<body>
  {% extends "base.html" %}
  
  {% block content %}
  <div class="container">

    <form class="form-signin" action="/register/" method="post">{%csrf_token%}
      <h3><div><b>{{ msg }}</b></div></h3>
      <h2 class="form-signin-heading text-center">Sign Up</h2>
      <label class="sr-only" for="id_firstname">First Name</label> 
      <input id="id_firstname" maxlength="50" name="firstname" type="text" class="form-control" placeholder="First Name" required autofocus />
      <label class="sr-only" for="id_lastname">Last Name</label> 
      <input id="id_lastname" maxlength="50" name="lastname" type="text" class="form-control" placeholder="Last Name" required autofocus />
      <label for="email" class="sr-only">Email</label>
      <input class="form-control" type="email" name="email" placeholder="Email" required autofocus>
      <label for="password" class="sr-only">Password</label>
      <input type="password" name="password" class="form-control" placeholder="Password" required>

      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>

  </div> <!-- /container -->
</body>
</html>
{% endblock %}

django/templates/upload.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Upload</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/upload.css">
    <style type="text/css">
      #loading {
        position: fixed;
        left: 0px;
        top: 0px;
        width: 100%;
        height: 100%;
        z-index: 9999;
        opacity: .95;
        background: url('/static/img/giphy.gif')50% 50% no-repeat rgb(249,249,249);
    `}
    </style>
  </head>
  <body>
    
  {% extends "base.html" %}
  
  {% block content %}
  <div id="loading"></div>
   <form method="post" id="form1"	action="/upload/" enctype="multipart/form-data" class="post-form">{% csrf_token %}
      <div class="header">
         <p class="center">Upload Your Audio File</p>
      </div>
      <div class="input">
        <label class="custom-file-upload" for="id_name"></label>
        <input class="button" id="id_name" name="name" type="file" required />
        <input type="submit" class="button" id="submit" value="Upload" onclick="myFunction()">
      </div>
    </form>
    {{ msg }}
  </body>
  <script src="/static/js/jquery.js"></script>
  <script type="text/javascript">
  $(window).ready(function() {
      $('#loading').hide();
  });
  function myFunction(){
    var fileName = $("#id_name").val();
    if(fileName) { 
        $('#loading').show();
    } 
  }
  </script>
</html>
{% endblock %}